package com.syntax.class34;


public class TryCatchFinally {
public static void main(String[] args) {
	
	
	division(10, 5);
	division(10, 0);
	
//public static void division(int num,int num1) {}	
}
	
	
public static void division(int num,int num1) {
	try {
		
		System.out.println(num/num1);
	}catch (ArithmeticException ae) {
		ae.printStackTrace();  //detailed message of an exception
		
		System.out.println(	ae.getMessage());   // provide friendly msg , this method  will give us message of an exception
		System.out.println();
	}
}	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	

}
